### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by leon** [davidje13/lean-qr#3]
When I try to use this library in Vite, it says that global is not defined.

I think you need to compile the lib as both ESM and CommonJS.
then change your package.jsons exports field to point to both versions.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by davidje13** [comment]
As part of adding SVG support just now, I changed the rollup config to build CommonJS rather than UMD, which should be more compatible with ES6 imports, so you might find this is no longer a problem in 1.3.0 (at least in NodeJS it tends to auto-detect it correctly, and I imagine webpack etc. will also figure it out with the same approach).

This does mean the library has dropped ASM and globals support, which I'm not sure about, but I think they're not widely used these days.

If you still see the issue let me know and I'll look at providing separate CommonJS and ES6 imports (or perhaps UMD and ES6 for widest compatibility).

**Comment by davidje13** [comment]
Since I haven't heard back I'm going to assume this has been fixed for you in 1.3.0 and close this issue, but if you're still having trouble please feel free to re-open.
