### ISSUE TITLE
Support ESM module format

### ISSUE THREAD

**Issue by leon** [davidje13/lean-qr#5]
When using lean-qr in my angular app it's warning me: `depends on 'lean-qr'. CommonJS or AMD dependencies can cause optimization bailouts.`

Would you consider adding an ESM build?

I don't know how much you know about the subject, but I can help you if needed :)

**Comment by davidje13** [comment]
So I had a look at this a few months ago ([branch](https://github.com/davidje13/lean-qr/tree/alternative-build)) but parked it because it didn't actually help for this library (the main export is a class with methods, so there's almost nothing to shake — even if you only use a single method, it can't guarantee the others won't get used dynamically)

I'm still a little hesitant to include 2 builds, but if there's a good reason to then I can merge that branch.

I see that Angular offers a `allowedCommonJsDependencies` option, which _might_ be more appropriate here (the warning is rather heavy-handed and doesn't account for the fact that this library has nothing to realistically shake). It would be good to see some kind of Angular-published source document that explains exactly what potential issues they're referring to (I'm assuming it's all about tree shaking, in which case it's a false-positive here, but maybe there's some other optimisation they avoid)

**Comment by leon** [comment]
It's not only about the treeshakability. if rollup, webpack, esbuild, swc or whatever bundler you are using is going to output for the browser it needs to recompile the commonjs to change the `require` calls.

By outputting esm they will not have to do as much work, and it will result in a smaller output.
but node is also going towards esm modules, so it future proofs the library also.

I hope this is enough to convince you, but I understand if you don't want to add the complexity now, in that case I can simply add the library to `allowedCommonJsDependencies ` :)

**Comment by davidje13** [comment]
I'll spend some time thinking about this. Module exports are for sure the future, but CJS is compatible with `import` in Node, webpack, and rollup (though notably not in the browser), and the major stand-out holding things back is Jest, which still doesn't support modules natively (and modules _don't_ easily convert back to CJS), so there are real pressures in the wider ecosystem to stay on CJS for now. Providing both builds (like in the branch I tried) is a viable option, but needs [more testing](https://github.com/davidje13/lean-qr/tree/master/test-package) because it increases the number of ways various tools and versions may choose to interact with it, so I don't know if it's worth it for a library as simple as this.

I'm tempted to wait until modules are mature enough that I can just switch this library to be module-only (which is a thing some libraries have done already, though typically this has caused various problems for users so seems a bit premature).

But as I say: not discounting this out-of-hand. I'll think about it.

**Comment by davidje13** [comment]
The latest version (2.2.0) now includes esm exports alongside cjs exports, and they should be used automatically when appropriate.

The main changes which enabled this are:

- the build now includes more robust automated testing of the packaged library, so I can have some confidence in the build for the different modes
- more `extras` have been added which can benefit from tree shaking (notably the react integration). The core library itself still does not benefit from tree shaking though

Let me know if you encounter any issues with it.
