### ISSUE TITLE
add toCanvas example to readme

### ISSUE THREAD

**Issue by moritzpflueger** [davidje13/lean-qr#6]
The Readme is missing what element should be used in the html template.

I played around with a `<div>`.

Looking through your example website I found the element should be a canvas with width and height.

* `<canvas id="my-canvas" width="1" height="1"></canvas>`

As someone who never used `<canvas>` before, this could be very helpful to include in the Readme.

I spent 3 hours on this.

Thank You!

**Comment by davidje13** [comment]
Sure; I've updated the readme to include a full example at the top and give more detail on the API commands `toCanvas` and `toSVG`. It isn't on NPM yet but will go out with the next version. Let me know if it's still unclear!

It's minor, but note that the `width` & `height` aren't strictly required; the demo sets them so that the canvas defaults to being square to avoid it jumping when it first renders (for whatever reason, `canvas` defaults to being 300x150 if no size is explicitly given). As soon as you actually render a QR code though, the width and height will be overridden to be whatever the actual size of your QR code is.

**Comment by moritzpflueger** [comment]
Thanks for the swift update! 🙏 I believe this will be very helpful to many.

I could have sworn the width and height made a difference :) Thanks for the info, this sounds solid.
